apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.configMapName }}
  labels:
    app: mysql
data:
  database: {{ .Values.mysql.configMap.databaseName  }}
  username: {{ .Values.mysql.configMap.username }}
