apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.secret.rootPassword }}
  user-password: {{ .Values.mysql.secret.userPassword }}
