apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpmyadmin.serviceName }}
spec:
  selector:
    app: {{ .Values.phpmyadmin.deploymentName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
