apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.phpmyadmin.deploymentName }}
  labels:
    app: {{ .Values.phpmyadmin.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.phpmyadmin.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.phpmyadmin.deploymentName }}
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          lifecycle:
            postStart:
              exec:
                command: 
                  - /bin/sh 
                  - -c
                  - mkdir /var/www/html/{{ .Values.phpmyadmin.ingressPath }}; mv /var/www/html/* /var/www/html/{{ .Values.phpmyadmin.ingressPath }}; mv /var/www/html/.* /var/www/html/{{ .Values.phpmyadmin.ingressPath }}; echo success!
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Values.mysql.serviceName }}
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: root-password

