apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.wordpress.persistence.volumeName }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.wordpress.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.wordpress.persistence.path }}
