mysql:
  image: mysql:5.6


  configMap:
    databaseName: wordpressdb
    username: wordpress
  secret:
    rootPassword: password
    userPassword: password
  persistence:
    size: 2Gi
    path: "/mnt/mysql-data"
    volumeName: "mysql-volume"
  deploymentName: "mysql-deployment"
  configMapName: "mysql-configmap"
  secretName: "mysql-secret"
  PVCName: "mysql-pv-claim"
  serviceName: "mysql-svc"

wordpress:
  image: wordpress:5.8-apache
  url: "wp.9craft.site"
  persistence:
    size: 2Gi
    path: "/mnt/wp-data"
    volumeName: "wordpress-volume"
  deploymentName: "wordpress-deployment"
  PVCName: "wordpress-pv-claim"
  serviceName: "wordpress-svc"
  ingressName: "wordpress-ing"

phpmyadmin:
  url: "pma.9craft.site"
  image: phpmyadmin/phpmyadmin
  deploymentName: "pma-deployment"
  serviceName: "pma-svc"
  ingressName: "pma-ing"



