- name: prepare cluster
  hosts: all
  become: true

  tasks:
    - name: Download helm script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: 644

    - name: Change script permission
      ansible.builtin.file: 
        dest: /tmp/get_helm.sh
        mode: a+x

    - name: Run helm installation script
      ansible.builtin.command: /tmp/get_helm.sh 

    - name: Add ingress-nginx repo
      kubernetes.core.helm_repository:
        name: stable
        repo_url: "https://kubernetes.github.io/ingress-nginx"
           
    - name: Deploy nginx
      kubernetes.core.helm:
          name: ingress-nginx
          chart_ref: stable/ingress-nginx
          release_namespace: default
          values:
            replicas: 1
            controller:
              hostNetwork: true

    - name: Copy helm chart
      ansible.builtin.copy:
        src: ../charts
        dest: /tmp/

    - name: Copy certs and pkey
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /tmp/
      with_items:
        - "../certs/fullchain.pem"
        - "../certs/privkey.pem"

    - name: Apply certs
      ansible.builtin.command: "kubectl create secret tls tls --key /tmp/privkey.pem --cert /tmp/fullchain.pem"

    - name: Waiting for ingress-nginx image to download
      ansible.builtin.pause:
        seconds: 60

    - name: Deploy helm chart
      kubernetes.core.helm:
        name: wp-mysql-pma
        chart_ref: /tmp/charts
        release_namespace: default
